import { readFileSync, writeFileSync } from 'node:fs';

const src = process.argv[2];
if (!src) { console.error('usage: build-comunas.mjs <shipping_municipalities.yml>'); process.exit(1); }

const lines = readFileSync(src, 'utf8').split('\n');
const comunas = [];
let inChile = false;
let region = null;

// Map of id -> official name for entries that need renaming
const renameMap = {
  '8261395': 'Santiago',
};

for (const line of lines) {
  if (/^CL:/.test(line)) { inChile = true; continue; }
  if (inChile && /^[A-Z]{2}:/.test(line)) break;
  if (!inChile) continue;
  const r = line.match(/^  '(\d+)':/);
  if (r) { region = r[1]; continue; }
  const m = line.match(/^    '(\d+)':\s*(.+?)\s*$/);
  if (m && region) {
    let name = m[2].replace(/^['"]|['"]$/g, '');
    // Strip inline comments (whitespace + # + rest of line)
    name = name.replace(/\s+#.*$/, '');
    // Apply rename map if id is in the map
    if (renameMap[m[1]]) {
      name = renameMap[m[1]];
    }
    comunas.push({ id: m[1], name, region });
  }
}
comunas.sort((a, b) => a.name.localeCompare(b.name, 'es'));

const out = `// Generated by scripts/build-comunas.mjs — do not edit by hand.
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else { root.Eta = root.Eta || {}; root.Eta.Comunas = factory(); }
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';
  return ${JSON.stringify(comunas)};
});
`;
writeFileSync(new URL('../src/eta-comunas.js', import.meta.url), out);
console.log(`wrote ${comunas.length} comunas`);
